### ISSUE TITLE
modulus

### ISSUE THREAD

**Issue by jason-todd-harris** [learn-co-curriculum/reading-ios-primitives-and-operators#3]
Results to the remainder of dividing the right operand by the left operand. Note: This does not perform the strict mathematical definition of modulus

should be changed to left hand divided by right hand

**Comment by markedwardmurray** [comment]
68871d1aeecf8a681545cb979a072fa8b6925a0e

Ha, thanks. I've had trouble with left and right since kindergarten. :-B
